top_lib_names = ["pandas","numpy","matplotlib","sklearn","seaborn","tensorflow","torch","xgboost","scipy","plotly","cv2","keras","lightgbm","torchvision","nltk","transformers","catboost","statsmodels","imblearn","wordcloud","missingno","optuna","skimage","datasets"]

builtin_exps_excluded = ["nameerror", "memoryerror", 
                         "pendingdeprecationwarning", "userwarning", 
                         "keyboardinterrupt", 
                         "modulenotfounderror", "importerror", "notimplementederror", 
                         "filenotfounderror", "fileexistserror", "isadirectoryerror", "notadirectoryerror","eoferror",  "permissionerror", "unicodeerror","unicodedecodeerror", 
                         "oserror", "ioerror", "brokenpipeerror", "blockingioerror",
                         "connectionerror", "connectionreseterror", "connectionrefusederror", "systemexit"]

err_lib_percent_cutoff_k = 0.5
err_lib_count_cutoff_k = 100

err_lib_percent_cutoff_g = 0.5
err_lib_count_cutoff_g = 400

check_lan_list =['assembly',
 'batchfile',
 'c',
 'c#',
 'c++',
 'clojure',
 'cmake',
 'cobol',
 'coffeescript',
 'css',
 'csv',
 'dart',
 'dm',
 'dockerfile',
 'elixir',
 'erlang',
 'fortran',
 'go',
 'groovy',
 'haskell',
 'html',
 'ini',
 'java',
 'javascript',
 'json',
 'julia',
 'kotlin',
 'lisp',
 'lua',
 'makefile',
 'markdown',
 'matlab',
 'objective-c',
 'ocaml',
 'pascal',
 'perl',
 'php',
 'powershell',
 'prolog',
 'python',
 'r',
 'ruby',
 'rust',
 'scala',
 'shell',
 'sql',
 'swift',
 'tex',
 'toml',
 'typescript',
 'verilog',
 'visual basic',
 'xml',
 'yaml']