top_lib_names = ["pandas","numpy","matplotlib","sklearn","seaborn","tensorflow","torch","xgboost","scipy","plotly","cv2","keras","lightgbm","torchvision","nltk","transformers","catboost","statsmodels","imblearn","wordcloud","missingno","optuna","skimage","datasets"]

builtin_exps_excluded = ["nameerror", "keyboardinterrupt", "modulenotfounderror", "filenotfounderror", "importerror", "oserror", "memoryerror", "ioerror","unicodeerror"]

lib_percent_cutoff = 0.8
err_lib_count_cutoff = 400

check_lan_list =['assembly',
 'batchfile',
 'c',
 'c#',
 'c++',
 'clojure',
 'cmake',
 'cobol',
 'coffeescript',
 'css',
 'csv',
 'dart',
 'dm',
 'dockerfile',
 'elixir',
 'erlang',
 'fortran',
 'go',
 'groovy',
 'haskell',
 'html',
 'ini',
 'java',
 'javascript',
 'json',
 'julia',
 'kotlin',
 'lisp',
 'lua',
 'makefile',
 'markdown',
 'matlab',
 'objective-c',
 'ocaml',
 'pascal',
 'perl',
 'php',
 'powershell',
 'prolog',
 'python',
 'r',
 'ruby',
 'rust',
 'scala',
 'shell',
 'sql',
 'swift',
 'tex',
 'toml',
 'typescript',
 'verilog',
 'visual basic',
 'xml',
 'yaml']